name: Build and Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build-image:
    name: Build
    runs-on: actuated
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Packer Init
        run: packer init .

      - name: Packer Build
        run: packer build .
