name: Build and Deploy

on:
  push:
    branches:
      - "main"
jobs:
  build-image:
    name: Build
    runs-on: actuated
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install qemu
        run: sudo apt-get update && sudo apt-get install qemu-system -y
      
      - name: Setup packer
        uses: hashicorp/setup-packer@main

      - name: Packer Init
        run: packer init .

      - name: Packer Build
        run: |
          sudo chmod o+rw /dev/kvm
          packer build .
